apply plugin: "com.android.library"

android {
    namespace "ir.shadfar.rexa"
    compileSdk project.hasProperty("compileSdkVersion") ? rootProject.ext.compileSdkVersion : 36

    defaultConfig {
        minSdk project.hasProperty("minSdkVersion") ? rootProject.ext.minSdkVersion : 23
        targetSdk project.hasProperty("targetSdkVersion") ? rootProject.ext.targetSdkVersion : 36
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(":capacitor-android")

    // وابستگی‌های AndroidX مورد نیاز برای RexaNativePlugin.java
    implementation "androidx.annotation:annotation:1.9.1"
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.appcompat:appcompat:1.7.0"
}
