apply plugin: "com.android.library"

android {
    namespace "ir.shadfar.rexa"
    compileSdk project.hasProperty("compileSdkVersion") ? rootProject.ext.compileSdkVersion : 36

    defaultConfig {
        minSdk project.hasProperty("minSdkVersion") ? rootProject.ext.minSdkVersion : 23
        targetSdk project.hasProperty("targetSdkVersion") ? rootProject.ext.targetSdkVersion : 36
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(":capacitor-android")
}
